# Generated by Django 4.1.7 on 2023-02-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
