# Generated by Django 4.1.7 on 2023-02-26 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.IntegerField()),
                ('weekday', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.teacherprofile')),
            ],
        ),
    ]
