# Generated by Django 4.1.7 on 2023-02-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timings', '0003_rename_subject_code1_timetable_code1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='code2',
            new_name='subject_code',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='code1',
        ),
    ]
